# Generated by Django 4.2.2 on 2023-06-27 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='producto',
            table='producto',
        ),
    ]
