# Generated by Django 4.2.2 on 2023-06-29 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0003_alter_recibo_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='log_anulados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField()),
                ('recibo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='venta.recibo')),
            ],
        ),
    ]
