# Generated by Django 4.2.2 on 2023-06-29 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0004_log_anulados'),
    ]

    operations = [
        migrations.AddField(
            model_name='recibo',
            name='fecha',
            field=models.DateTimeField(auto_created=True, null=True),
        ),
    ]
