# Generated by Django 4.2.2 on 2023-06-29 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0005_recibo_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recibo',
            name='fecha',
            field=models.DateTimeField(auto_created=True, auto_now=True, null=True),
        ),
    ]
