# Generated by Django 4.2.2 on 2023-07-04 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0006_alter_recibo_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recibo',
            name='fecha',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
