# Generated by Django 4.2.2 on 2023-07-06 19:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0007_alter_recibo_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recibo',
            name='fecha',
            field=models.DateTimeField(auto_created=True, default=django.utils.timezone.now),
        ),
    ]
