# Generated by Django 4.2.2 on 2024-04-09 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0008_alter_recibo_fecha'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='log_anulados',
            new_name='LogAnulados',
        ),
        migrations.AlterModelTable(
            name='loganulados',
            table='log_anulados',
        ),
    ]
